spring:
  profiles:
    active: mongo-atlas
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
tweet:
  app:
    jwtSecret: dokfdsjgfdslkgjfdkkgewiukhjsdkjhf
    jwtExpirationMs: 7200000
---
spring:
  config:
    activate:
      on-profile: local-with-kafka
  kafka:
    template:
      default-topic: new-tweet
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: new-tweet-listener-group
    producer:
      bootstrap-servers: localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093
      enable: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tweet-app 

---
spring:
  config:
    activate:
      on-profile: local-without-kafka
  kafka:
    enable: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tweet-app 

---
spring:
  config:
    activate:
      on-profile: mongo-atlas
  kafka:
    enable: false
  data:
    mongodb:
      uri: mongodb+srv://striders:q0qYosTL8IeN5MtO@cluster0.woe3d.mongodb.net/?retryWrites=true&w=majority
      database: tweet-app 
         
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    template:
      default-topic: new-tweet
    consumer:
      bootstrap-servers: dev:9092,dev:9093
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers: dev:9092,dev:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093
  data:
    mongodb:
      host: dev
      port: 27017
      database: tweet-app 